<?xml version ="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

   <xacro:include filename="$(find my_robot2_description)/urdf/common_properties.xacro" />
   <xacro:include filename="$(find my_robot2_description)/urdf/mobile_base.xacro" />
   <xacro:include filename="$(find my_robot2_description)/urdf/mobile_base_gazebo.xacro" /> 
   <xacro:include filename="$(find my_robot2_description)/urdf/arm.xacro" /> 
   <xacro:include filename="$(find my_robot2_description)/urdf/arm_gazebo.xacro" /> 

   <joint name="mobile_base_arm_joint" type="fixed">
      <parent link="base_link" />
      <child link="arm_base_link" />
      <origin xyz="${base_length / 4.0 } 0 ${base_height}" rpy="0 0 0" />
   </joint>
   <!-- <xacro:include filename="$(find my_robot2_description)/urdf/camera.xacro" /> -->
</robot>   
     

 

